"""Add retries to outbox

Revision ID: 6de24b6e387e
Revises: 7c3fc5dbb1a6
Create Date: 2026-03-10 21:20:27.636416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6de24b6e387e'
down_revision: Union[str, None] = '7c3fc5dbb1a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('retries', sa.Integer(), nullable=False))
    op.add_column('outbox_events', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('current_balance_cents', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_balance_cents')
    op.drop_column('outbox_events', 'next_retry_at')
    op.drop_column('outbox_events', 'retries')
    # ### end Alembic commands ###
