from pydantic import BaseModel, Field
from typing import Dict, Optional, Any

class PurchaseEvaluateRequest(BaseModel):
    item_name: str = Field(..., min_length=1, max_length=255)
    price_cents: int = Field(..., ge=1)
    category: str = Field("General", max_length=100)

class PurchaseEvaluateResponse(BaseModel):
    purchase_id: str
    affordability_score: int
    risk_level: str
    days_impacted: float
    liquidity_failure: bool
    deficit_mode: bool
    goals_delayed: Dict[str, float]
    goal_delay_days: Dict[str, Any] = {}
    risk_breakdown: Dict[str, Any] = {}
    behavior_penalty: float = 0.0
    behavior_explanation: str = ""
    ai_insight: str  # Generated by Gemini LLM service
