from pydantic import BaseModel
from typing import Dict

class PurchaseEvaluateRequest(BaseModel):
    item_name: str
    price_cents: int
    category: str = "General"

class PurchaseEvaluateResponse(BaseModel):
    purchase_id: str
    affordability_score: int
    risk_level: str
    days_impacted: float
    liquidity_failure: bool
    deficit_mode: bool
    goals_delayed: Dict[str, float]
    ai_insight: str  # Generated by Gemini LLM service
